<<<<<<< HEAD
# Generated by Django 2.2.4 on 2019-09-04 16:24
=======
# Generated by Django 2.2 on 2019-05-12 19:59
>>>>>>> 95068951492bb06b2a04cd6fb5a4f2d14b164638

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter_name', models.CharField(default='Adapter', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(default='Host', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Preamble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pa_subnet_name', models.CharField(default='pre', max_length=50)),
                ('ttl', models.CharField(max_length=50)),
                ('retry', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=50)),
                ('name_server', models.CharField(max_length=50)),
                ('email_addr', models.CharField(max_length=20)),
                ('expiry', models.CharField(max_length=50)),
                ('refresh', models.CharField(max_length=50)),
                ('nxdomain_ttl', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(default='Role', max_length=50)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subnet_name', models.CharField(default='Sub', max_length=128)),
                ('preamble', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subnet', to='ipam.Preamble')),
                ('role', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnet', to='ipam.Role')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA'), ('ALIAS', 'ALIAS'), ('cname', 'cname'), ('MX', 'MX'), ('NS', 'NS'), ('PTR', 'PTR'), ('SOA', 'SOA')], max_length=8)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='ipam.Host')),
            ],
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=18)),
                ('adapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mac', to='ipam.Adapter')),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv4', models.CharField(blank=True, max_length=12, null=True)),
                ('ipv6', models.CharField(blank=True, max_length=40, null=True)),
                ('mac_addr', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IP', to='ipam.Mac')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='IP', to='ipam.Subnet')),
            ],
        ),
        migrations.AddField(
            model_name='adapter',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter', to='ipam.Host'),
        ),
    ]
